#### Convert text to a numerical representation callled a feature vector = list of numbers

In [1]:
measurements=[{'city':'Dubai','temperture':33.},{'city':'London','temperture':12.},{'city':'San Francisco','temperture':18.},]
measurements

[{'city': 'Dubai', 'temperture': 33.0},
 {'city': 'London', 'temperture': 12.0},
 {'city': 'San Francisco', 'temperture': 18.0}]

#### Transform lists of feature-value mappings to vectors

In [60]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer()

In [61]:
vec.fit_transform(measurements).toarray()

array([[ 1.,  0.,  0., 33.],
       [ 0.,  1.,  0., 12.],
       [ 0.,  0.,  1., 18.]])

In [62]:
vec.get_feature_names()

['city=Dubai', 'city=London', 'city=San Francisco', 'temperture']

## Convert a collection of text documents to a matrix of token counts

In [70]:
corpus=['Mcmaster BDA 102 is an interesting course','I cannot wait for Sunday!',
        'McMaster student shall use BDA 102 to successfully combat skynet',
        'Terminators you are not going down',
        'Sarah Conor is out of your reach']

In [71]:
print(type(corpus))

<class 'list'>


In [72]:
print(len(corpus))

5


In [73]:
print(corpus)

['Mcmaster BDA 102 is an interesting course', 'I cannot wait for Sunday!', 'McMaster student shall use BDA 102 to successfully combat skynet', 'Terminators you are not going down', 'Sarah Conor is out of your reach']


In [76]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [77]:
result=vectorizer.fit_transform(corpus).todense()
# todense() converts to a sparse matrix

In [78]:
print(result)

[[1 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1]]


In [80]:
print(vectorizer.vocabulary_)

{'mcmaster': 13, 'bda': 3, '102': 0, 'is': 12, 'an': 1, 'interesting': 11, 'course': 7, 'cannot': 4, 'wait': 27, 'for': 9, 'sunday': 23, 'student': 21, 'shall': 19, 'use': 26, 'to': 25, 'successfully': 22, 'combat': 5, 'skynet': 20, 'terminators': 24, 'you': 28, 'are': 2, 'not': 14, 'going': 10, 'down': 8, 'sarah': 18, 'conor': 6, 'out': 16, 'of': 15, 'your': 29, 'reach': 17}


In [81]:
import pandas as pd
df=pd.DataFrame(vectorizer.transform(corpus).toarray(),
               columns=vectorizer.get_feature_names())
df

102  an  are  bda  cannot  combat  conor  course  down  for  ...   skynet  \
0    1   1    0    1       0       0      0       1     0    0  ...        0   
1    0   0    0    0       1       0      0       0     0    1  ...        0   
2    1   0    0    1       0       1      0       0     0    0  ...        1   
3    0   0    1    0       0       0      0       0     1    0  ...        0   
4    0   0    0    0       0       0      1       0     0    0  ...        0   

   student  successfully  sunday  terminators  to  use  wait  you  your  
0        0             0       0            0   0    0     0    0     0  
1        0             0       1            0   0    0     1    0     0  
2        1             1       0            0   1    1     0    0     0  
3        0             0       0            1   0    0     0    1     0  
4        0             0       0            0   0    0     0    0     1  

[5 rows x 30 columns]

### Application

In [82]:
train_set=['The sky is blue.','The sun is bright.']
test_set=['The sun in the sky is bright.','We can see the shining sun, the bright sun','sky is blue']

In [83]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(stop_words='english')
result=vectorizer.fit_transform(train_set).todense()
print(result)

[[1 0 1 0]
 [0 1 0 1]]


In [84]:
print(vectorizer.vocabulary_)

{'sky': 2, 'blue': 0, 'sun': 3, 'bright': 1}


In [85]:
print(vectorizer.vocabulary_)

{'sky': 2, 'blue': 0, 'sun': 3, 'bright': 1}


## Class Activity

### Create a list with variables containing each text messages

In [86]:
avengers1='Avengers: Age of Ultron is a 2015 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2012s The Avengers and the eleventh film in the Marvel Cinematic Universe (MCU). The film was written and directed by Joss Whedon and features an ensemble cast that includes Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Jeremy Renner, Don Cheadle, Aaron Taylor-Johnson, Elizabeth Olsen, Paul Bettany, Cobie Smulders, Anthony Mackie, Hayley Atwell, Idris Elba, Stellan Skarsgård, James Spader, and Samuel L. Jackson. In Avengers: Age of Ultron, the Avengers fight Ultron, an artificial intelligence obsessed with causing human extinction'
avengers2='Avengers: Infinity War is a 2018 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2012s The Avengers and 2015s Avengers: Age of Ultron, and the nineteenth film in the Marvel Cinematic Universe (MCU). The film is directed by Anthony and Joe Russo, written by Christopher Markus and Stephen McFeely, and features an ensemble cast including Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Benedict Cumberbatch, Don Cheadle, Tom Holland, Chadwick Boseman, Paul Bettany, Elizabeth Olsen, Anthony Mackie, Sebastian Stan, Danai Gurira, Letitia Wright, Dave Bautista, Zoe Saldana, Josh Brolin, and Chris Pratt. In Avengers: Infinity War, the Avengers and the Guardians of the Galaxy attempt to stop Thanos from amassing the all-powerful Infinity Stones'

In [87]:
avengers_train=[avengers1,avengers2]

### Build vocabulary and then print array for the list

In [94]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(stop_words='english')

In [95]:
vectorizer.fit_transform(avengers_train)

<2x113 sparse matrix of type '<class 'numpy.int64'>'
	with 158 stored elements in Compressed Sparse Row format>

In [96]:
#vectorizer.fit_transform(avengers_train).todense()

In [97]:
print(vectorizer.vocabulary_)

{'avengers': 12, 'age': 5, 'ultron': 105, '2015': 1, 'american': 7, 'superhero': 100, 'film': 44, 'based': 13, 'marvel': 70, 'comics': 27, 'team': 102, 'produced': 81, 'studios': 99, 'distributed': 33, 'walt': 107, 'disney': 32, 'motion': 73, 'pictures': 78, 'sequel': 90, '2012s': 0, 'eleventh': 37, 'cinematic': 25, 'universe': 106, 'mcu': 72, 'written': 111, 'directed': 31, 'joss': 64, 'whedon': 109, 'features': 42, 'ensemble': 39, 'cast': 19, 'includes': 53, 'robert': 83, 'downey': 35, 'jr': 65, 'chris': 23, 'hemsworth': 49, 'mark': 68, 'ruffalo': 84, 'evans': 40, 'scarlett': 88, 'johansson': 61, 'jeremy': 59, 'renner': 82, 'don': 34, 'cheadle': 22, 'aaron': 4, 'taylor': 101, 'johnson': 62, 'elizabeth': 38, 'olsen': 76, 'paul': 77, 'bettany': 16, 'cobie': 26, 'smulders': 92, 'anthony': 8, 'mackie': 67, 'hayley': 48, 'atwell': 11, 'idris': 52, 'elba': 36, 'stellan': 95, 'skarsgård': 91, 'james': 58, 'spader': 93, 'samuel': 87, 'jackson': 57, 'fight': 43, 'artificial': 9, 'intelligence

In [98]:
import pandas as pd
df=pd.DataFrame(vectorizer.transform(avengers_train).toarray(),columns=vectorizer.get_feature_names())
df

2012s  2015  2015s  2018  aaron  age  amassing  american  anthony  \
0      1     1      0     0      1    2         0         1        1   
1      1     0      1     1      0    1         1         1        2   

   artificial ...   thanos  tom  ultron  universe  walt  war  whedon  wright  \
0           1 ...        0    0       3         1     1    0       1       0   
1           0 ...        1    1       1         1     1    2       0       1   

   written  zoe  
0        1    0  
1        1    1  

[2 rows x 113 columns]

### Sum the two rows and build a frequency table

In [100]:
avengersSum=df.sum()
print(avengersSum)

2012s           2
2015            1
2015s           1
2018            1
aaron           1
age             3
amassing        1
american        2
anthony         3
artificial      1
attempt         1
atwell          1
avengers       11
based           2
bautista        1
benedict        1
bettany         2
boseman         1
brolin          1
cast            2
causing         1
chadwick        1
cheadle         2
chris           5
christopher     1
cinematic       2
cobie           1
comics          2
cumberbatch     1
danai           1
               ..
robert          2
ruffalo         2
russo           1
saldana         1
samuel          1
scarlett        2
sebastian       1
sequel          2
skarsgård       1
smulders        1
spader          1
stan            1
stellan         1
stephen         1
stones          1
stop            1
studios         4
superhero       4
taylor          1
team            2
thanos          1
tom             1
ultron          4
universe        2
walt      

### Check type and see whether it is a dataframe

In [30]:
type(avengersSum)

pandas.core.series.Series

### If not dataframe, convert it to a dataframe

In [101]:
avengersSum=avengersSum.to_frame()
print(avengersSum)

              0
2012s         2
2015          1
2015s         1
2018          1
aaron         1
age           3
amassing      1
american      2
anthony       3
artificial    1
attempt       1
atwell        1
avengers     11
based         2
bautista      1
benedict      1
bettany       2
boseman       1
brolin        1
cast          2
causing       1
chadwick      1
cheadle       2
chris         5
christopher   1
cinematic     2
cobie         1
comics        2
cumberbatch   1
danai         1
...          ..
robert        2
ruffalo       2
russo         1
saldana       1
samuel        1
scarlett      2
sebastian     1
sequel        2
skarsgård     1
smulders      1
spader        1
stan          1
stellan       1
stephen       1
stones        1
stop          1
studios       4
superhero     4
taylor        1
team          2
thanos        1
tom           1
ultron        4
universe      2
walt          2
war           2
whedon        1
wright        1
written       2
zoe           1

[113 ro

In [102]:
print(avengersSum.shape)

(113, 1)


### To this dataframe give a column name

In [33]:
avengersSum.columns=['frequency']

In [34]:
print(avengersSum)

             frequency
2012s                2
2015                 1
2015s                1
2018                 1
aaron                1
age                  3
amassing             1
american             2
anthony              3
artificial           1
attempt              1
atwell               1
avengers            11
based                2
bautista             1
benedict             1
bettany              2
boseman              1
brolin               1
cast                 2
causing              1
chadwick             1
cheadle              2
chris                5
christopher          1
cinematic            2
cobie                1
comics               2
cumberbatch          1
danai                1
...                ...
robert               2
ruffalo              2
russo                1
saldana              1
samuel               1
scarlett             2
sebastian            1
sequel               2
skarsgård            1
smulders             1
spader               1
stan       